# 明確指定 Python 專案
providers = ["python"]

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "postgresql"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 scripts/migrate.py && python3 main.py"
